controller_manager:
  ros__parameters:
    update_rate: 40 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    joints:
      - ak80_8_joint
    # use_local_topics:
    #   - /joint_states := /dar/joint_states

forward_position_controller:
  ros__parameters:
    joints:
      - ak80_8_joint
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - ak80_8_joint
    interface_name: velocity