controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ## Lest arm
    left_arm_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    left_arm_position_controller:
      type: forward_command_controller/ForwardCommandController
      
    left_arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    left_arm_effort_controller:
      type: forward_command_controller/ForwardCommandController

    ## Right arm
    right_arm_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    right_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_effort_controller:
      type: forward_command_controller/ForwardCommandController

left_arm_fts_broadcaster:
  ros__parameters:
    sensor_name: left_leptrino_fts
    frame_id: left_tool_link

left_arm_position_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: position

left_arm_velocity_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: velocity

left_arm_effort_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: effort

## Right arm
right_arm_fts_broadcaster:
  ros__parameters:
    sensor_name: right_leptrino_fts
    frame_id: right_tool_link

right_arm_position_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: position

right_arm_velocity_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: velocity

right_arm_effort_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: effort