controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      
    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController


joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
    # use_local_topics:
    #   - /joint_states := /levion/joint_states

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: velocity

forward_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: effort